export const picksConst = {
  'Zeus': [
    {team: 'Washington Wizards', ou: 'over', line: 33.5},
    {team: 'San Antonio Spurs', ou: 'over', line: 28.5},
    {team: 'Houston Rockets', ou: 'under', line: 27.5},
    {team: 'Phoenix Suns', ou: 'over', line: 51.5},
    {team: 'Memphis Grizzlies', ou: 'over', line: 41.5},
    {team: 'Miami Heat', ou: 'under', line: 48.5},
    {team: 'Oklahoma City Thunder', ou: 'under', line: 23.5},
    {team: 'Utah Jazz', ou: 'under', line: 51.5},
  ],
  'Chris': [
    {team: 'Utah Jazz', ou: 'over', line: 51.5},
    {team: 'Brooklyn Nets', ou: 'over', line: 56.5},
    {team: 'Minnesota Timberwolves', ou: 'under', line: 34.5},
    {team: 'Orlando Magic', ou: 'under', line: 22.5},
    {team: 'Chicago Bulls', ou: 'under', line: 42.5},
    {team: 'Los Angeles Clippers', ou: 'over', line: 42.5},
    {team: 'Detroit Pistons', ou: 'under', line: 24.5},
    {team: 'Toronto Raptors', ou: 'under', line: 35.5},
  ],
  'Adam': [
    {team: 'Milwaukee Bucks', ou: 'over', line: 54.5},
    {team: 'Houston Rockets', ou: 'over', line: 27.5},
    {team: 'Philadelphia 76ers', ou: 'over', line: 50.5},
    {team: 'Los Angeles Lakers', ou: 'over', line: 51.5},
    {team: 'Golden State Warriors', ou: 'over', line: 48.5},
    {team: 'Portland Trail Blazers', ou: 'under', line: 44.5},
    {team: 'Sacramento Kings', ou: 'over', line: 36.5},
    {team: 'Washington Wizards', ou: 'under', line: 33.5},
  ],
  'Billy': [
    {team: 'Cleveland Cavaliers', ou: 'over', line: 26.5},
    {team: 'Brooklyn Nets', ou: 'under', line: 56.5},
    {team: 'Memphis Grizzlies', ou: 'under', line: 41.5},
    {team: 'New Orleans Pelicans', ou: 'under', line: 39.5},
    {team: 'Toronto Raptors', ou: 'over', line: 35.5},
    {team: 'New York Knicks', ou: 'under', line: 41.5},
    {team: 'Boston Celtics', ou: 'over', line: 45.5},
    {team: 'Phoenix Suns', ou: 'under', line: 51.5},
  ],
  'Amir': [
    {team: 'New York Knicks', ou: 'over', line: 41.5},
    {team: 'Charlotte Hornets', ou: 'over', line: 38.5},
    {team: 'Orlando Magic', ou: 'over', line: 22.5},
    {team: 'Sacramento Kings', ou: 'under', line: 36.5},
    {team: 'Boston Celtics', ou: 'under', line: 45.5},
    {team: 'Dallas Mavericks', ou: 'over', line: 48.5},
    {team: 'Indiana Pacers', ou: 'under', line: 42.5},
    {team: 'Miami Heat', ou: 'over', line: 48.5},
  ],
  'Jesse': [
    {team: 'Atlanta Hawks', ou: 'over', line: 46.5},
    {team: 'Denver Nuggets', ou: 'over', line: 47.5},
    {team: 'Chicago Bulls', ou: 'over', line: 42.5},
    {team: 'Philadelphia 76ers', ou: 'under', line: 50.5},
    {team: 'Detroit Pistons', ou: 'over', line: 24.5},
    {team: 'Cleveland Cavaliers', ou: 'under', line: 26.5},
    {team: 'Charlotte Hornets', ou: 'under', line: 38.5},
    {team: 'Minnesota Timberwolves', ou: 'over', line: 34.5},
  ],
  'Martin': [
    {team: 'Portland Trail Blazers', ou: 'over', line: 44.5},
    {team: 'Los Angeles Clippers', ou: 'under', line: 42.5},
    {team: 'Los Angeles Lakers', ou: 'under', line: 51.5},
    {team: 'Golden State Warriors', ou: 'under', line: 48.5},
    {team: 'Indiana Pacers', ou: 'over', line: 42.5},
    {team: 'Oklahoma City Thunder', ou: 'over', line: 23.5},
    {team: 'Milwaukee Bucks', ou: 'under', line: 54.5},
    {team: 'Dallas Mavericks', ou: 'under', line: 48.5},
  ],
  'Leftovers': [
    {team: 'Atlanta Hawks', ou: 'under', line: 46.5},
    {team: 'Denver Nuggets', ou: 'under', line: 47.5},
    {team: 'New Orleans Pelicans', ou: 'over', line: 39.5},
    {team: 'San Antonio Spurs', ou: 'under', line: 28.5},
  ]
}