exports.picksConst = {
  'Adam': [
    {team: 'Orlando Magic', ou: 'over', line: 26.5, pos: 1},
    {team: 'Detroit Pistons', ou: 'over', line: 29.5, pos: 2},
    {team: 'New York Knicks', ou: 'over', line: 38.5, pos: 3},
    {team: 'Minnesota Timberwolves', ou: 'under', line: 48.5, pos: 4},
    {team: 'Brooklyn Nets', ou: 'over', line: 50.5, pos: 5},
    {team: 'Cleveland Cavaliers', ou: 'over', line: 47.5, pos: 6},
    {team: 'Memphis Grizzlies', ou: 'under', line: 48.5, pos: 7},
    {team: 'Phoenix Suns', ou: 'over', line: 52.5, pos: 8},
  ],
  'Zeus': [
    {team: 'Sacramento Kings', ou: 'over', line: 33.5, pos: 1},
    {team: 'Philadelphia 76ers', ou: 'over', line: 50.5, pos: 2},
    {team: 'Portland Trail Blazers', ou: 'under', line: 39.5, pos: 3},
    {team: 'Atlanta Hawks', ou: 'over', line: 45.5, pos: 4},
    {team: 'New York Knicks', ou: 'under', line: 38.5, pos: 5},
    {team: 'Indiana Pacers', ou: 'over', line: 23.5, pos: 6},
    {team: 'Washington Wizards', ou: 'over', line: 35.5, pos: 7},
    {team: 'Milwaukee Bucks', ou: 'under', line: 52.5, pos: 8},
  ],
  'Billy': [
    {team: 'Denver Nuggets', ou: 'over', line: 49.5, pos: 1},
    {team: 'Phoenix Suns', ou: 'under', line: 52.5, pos: 2},
    {team: 'Dallas Mavericks', ou: 'under', line: 48.5, pos: 3},
    {team: 'Houston Rockets', ou: 'over', line: 23.5, pos: 4},
    {team: 'Memphis Grizzlies', ou: 'over', line: 48.5, pos: 5},
    {team: 'Atlanta Hawks', ou: 'under', line: 45.5, pos: 6},
    {team: 'Chicago Bulls', ou: 'over', line: 41.5, pos: 7},
    {team: 'Cleveland Cavaliers', ou: 'under', line: 47.5, pos: 8},
  ],
  'Marty': [
    {team: 'Oklahoma City Thunder', ou: 'under', line: 23.5, pos: 1},
    {team: 'Washington Wizards', ou: 'under', line: 35.5, pos: 2},
    {team: 'Portland Trail Blazers', ou: 'over', line: 39.5, pos: 3},
    {team: 'Houston Rockets', ou: 'under', line: 23.5, pos: 4},
    {team: 'Brooklyn Nets', ou: 'under', line: 50.5, pos: 5},
    {team: 'Sacramento Kings', ou: 'under', line: 33.5, pos: 6},
    {team: 'Toronto Raptors', ou: 'under', line: 45.5, pos: 7},
    {team: 'Charlotte Hornets', ou: 'over', line: 35.5, pos: 8},
  ],
  'Jesse': [
    {team: 'Boston Celtics', ou: 'under', line: 53.5, pos: 1},
    {team: 'Charlotte Hornets', ou: 'under', line: 35.5, pos: 2},
    {team: 'Milwaukee Bucks', ou: 'over', line: 52.5, pos: 3},
    {team: 'Utah Jazz', ou: 'under', line: 24.5, pos: 4},
    {team: 'Los Angeles Clippers', ou: 'under', line: 52.5, pos: 5},
    {team: 'Miami Heat', ou: 'under', line: 48.5, pos: 6},
    {team: 'Dallas Mavericks', ou: 'over', line: 48.5, pos: 7},
    {team: 'Los Angeles Lakers', ou: 'over', line: 45.5, pos: 8},
  ],
  'Chris': [
    {team: 'San Antonio Spurs', ou: 'under', line: 22.5, pos: 1},
    {team: 'Golden State Warriors', ou: 'over', line: 51.5, pos: 2},
    {team: 'Indiana Pacers', ou: 'under', line: 23.5, pos: 3},
    {team: 'Los Angeles Lakers', ou: 'under', line: 45.5, pos: 4},
    {team: 'Los Angeles Clippers', ou: 'over', line: 52.5, pos: 5},
    {team: 'Miami Heat', ou: 'over', line: 48.5, pos: 6},
    {team: 'Minnesota Timberwolves', ou: 'over', line: 48.5, pos: 7},
    {team: 'Oklahoma City Thunder', ou: 'over', line: 23.5, pos: 8},
  ],
  'Amir': [
    {team: 'New Orleans Pelicans', ou: 'over', line: 44.5, pos: 1},
    {team: 'Toronto Raptors', ou: 'over', line: 45.5, pos: 2},
    {team: 'San Antonio Spurs', ou: 'over', line: 22.5, pos: 3},
    {team: 'Chicago Bulls', ou: 'under', line: 41.5, pos: 4},
    {team: 'Golden State Warriors', ou: 'under', line: 51.5, pos: 5},
    {team: 'Detroit Pistons', ou: 'under', line: 29.5, pos: 6},
    {team: 'Philadelphia 76ers', ou: 'under', line: 50.5, pos: 7},
    {team: 'Boston Celtics', ou: 'over', line: 53.5, pos: 8},
  ],
  'Leftovers': [
    {team: 'Denver Nuggets', ou: 'under', line: 49.5},
    {team: 'New Orleans Pelicans', ou: 'under', line: 44.5},
    {team: 'Orlando Magic', ou: 'under', line: 26.5},
    {team: 'Utah Jazz', ou: 'over', line: 24.5},
  ]
}