exports.picksConst = {
  Marty: [
    { team: 'MEM', ou: 'under', line: 47.5, pos: 1 },
    { team: 'MIA', ou: 'under', line: 44.5, pos: 2 },
    { team: 'SAC', ou: 'over', line: 46.5, pos: 3 },
    { team: 'SAS', ou: 'under', line: 35.5, pos: 4 },
    { team: 'POR', ou: 'over', line: 21.5, pos: 5 },
    { team: 'OKC', ou: 'under', line: 56.5, pos: 6 },
    { team: 'GSW', ou: 'under', line: 43.5, pos: 7 },
    { team: 'MIN', ou: 'over', line: 52.5, pos: 8 },
  ],
  Adam: [
    { team: 'ORL', ou: 'over', line: 47.5, pos: 1 },
    { team: 'MIL', ou: 'over', line: 50.5, pos: 2 },
    { team: 'DEN', ou: 'over', line: 51.5, pos: 3 },
    { team: 'CHI', ou: 'under', line: 27.5, pos: 4 },
    { team: 'NOP', ou: 'over', line: 45.5, pos: 5 },
    { team: 'MIA', ou: 'over', line: 44.5, pos: 6 },
    { team: 'NYK', ou: 'under', line: 54.5, pos: 7 },
    { team: 'SAS', ou: 'over', line: 35.5, pos: 8 },
  ],
  'Ztanz Nation': [
    { team: 'CLE', ou: 'over', line: 47.5, pos: 1 },
    { team: 'DAL', ou: 'over', line: 49.5, pos: 2 },
    { team: 'MIL', ou: 'under', line: 50.5, pos: 3 },
    { team: 'POR', ou: 'under', line: 21.5, pos: 4 },
    { team: 'DEN', ou: 'under', line: 51.5, pos: 5 },
    { team: 'ATL', ou: 'over', line: 35.5, pos: 6 },
    { team: 'WAS', ou: 'under', line: 20.5, pos: 7 },
    { team: 'CHA', ou: 'under', line: 29.5, pos: 8 },
  ],
  Amir: [
    { team: 'PHX', ou: 'under', line: 46.5, pos: 1 },
    { team: 'TOR', ou: 'over', line: 30.5, pos: 2 },
    { team: 'NOP', ou: 'under', line: 45.5, pos: 3 },
    { team: 'HOU', ou: 'under', line: 42.5, pos: 4 },
    { team: 'PHI', ou: 'over', line: 52.5, pos: 5 },
    { team: 'BKN', ou: 'over', line: 19.5, pos: 6 },
    { team: 'UTA', ou: 'over', line: 28.5, pos: 7 },
    { team: 'LAC', ou: 'over', line: 40.5, pos: 8 },
  ],
  Chris: [
    { team: 'OKC', ou: 'over', line: 56.5, pos: 1 },
    { team: 'BOS', ou: 'over', line: 58.5, pos: 2 },
    { team: 'MEM', ou: 'over', line: 47.5, pos: 3 },
    { team: 'UTA', ou: 'under', line: 28.5, pos: 4 },
    { team: 'TOR', ou: 'under', line: 30.5, pos: 5 },
    { team: 'BKN', ou: 'under', line: 19.5, pos: 6 },
    { team: 'LAL', ou: 'under', line: 43.5, pos: 7 },
    { team: 'SAC', ou: 'under', line: 46.5, pos: 8 },
  ],
  Billy: [
    { team: 'GSW', ou: 'over', line: 43.5, pos: 1 },
    { team: 'IND', ou: 'over', line: 47.5, pos: 2 },
    { team: 'MIN', ou: 'under', line: 52.5, pos: 3 },
    { team: 'CHA', ou: 'over', line: 29.5, pos: 4 },
    { team: 'ORL', ou: 'under', line: 47.5, pos: 5 },
    { team: 'HOU', ou: 'over', line: 42.5, pos: 6 },
    { team: 'CHI', ou: 'over', line: 27.5, pos: 7 },
    { team: 'ATL', ou: 'under', line: 35.5, pos: 8 },
  ],
  Jesse: [
    { team: 'PHX', ou: 'over', line: 46.5, pos: 1 },
    { team: 'LAC', ou: 'under', line: 40.5, pos: 2 },
    { team: 'NYK', ou: 'over', line: 54.5, pos: 3 },
    { team: 'DET', ou: 'over', line: 25.5, pos: 4 },
    { team: 'IND', ou: 'under', line: 47.5, pos: 5 },
    { team: 'BOS', ou: 'under', line: 58.5, pos: 6 },
    { team: 'LAL', ou: 'over', line: 43.5, pos: 7 },
    { team: 'PHI', ou: 'under', line: 52.5, pos: 8 },
  ],
  Leftovers: [
    { team: 'WAS', ou: 'over', line: 20.5 },
    { team: 'DET', ou: 'under', line: 25.5 },
    { team: 'CLE', ou: 'under', line: 47.5 },
    { team: 'DAL', ou: 'under', line: 49.5 },
  ],
};

picksConst2024 = {
  Amir: [
    { team: 'DAL', ou: 'under', line: 43.5, pos: 1 },
    { team: 'NYK', ou: 'over', line: 45.5, pos: 2 },
    { team: 'POR', ou: 'under', line: 27.5, pos: 3 },
    { team: 'MEM', ou: 'under', line: 44.5, pos: 4 },
    { team: 'LAL', ou: 'over', line: 46.5, pos: 5 },
    { team: 'HOU', ou: 'under', line: 31.5, pos: 6 },
    { team: 'PHI', ou: 'over', line: 47.5, pos: 7 },
    { team: 'SAC', ou: 'under', line: 44.5, pos: 8 },
  ],
  Jesse: [
    { team: 'IND', ou: 'over', line: 38.5, pos: 1 },
    { team: 'GSW', ou: 'under', line: 47.5, pos: 2 },
    { team: 'OKC', ou: 'under', line: 44.5, pos: 3 },
    { team: 'MIA', ou: 'over', line: 44.5, pos: 4 },
    { team: 'CLE', ou: 'under', line: 50.5, pos: 5 },
    { team: 'BKN', ou: 'under', line: 37.5, pos: 6 },
    { team: 'BOS', ou: 'under', line: 54.5, pos: 7 },
    { team: 'ATL', ou: 'under', line: 42.5, pos: 8 },
  ],
  Chris: [
    { team: 'PHX', ou: 'under', line: 52.5, pos: 1 },
    { team: 'CLE', ou: 'over', line: 50.5, pos: 2 },
    { team: 'DEN', ou: 'over', line: 52.5, pos: 3 },
    { team: 'NOP', ou: 'over', line: 44.5, pos: 4 },
    { team: 'BKN', ou: 'over', line: 37.5, pos: 5 },
    { team: 'DAL', ou: 'over', line: 43.5, pos: 6 },
    { team: 'DET', ou: 'over', line: 27.5, pos: 7 },
    { team: 'MIN', ou: 'under', line: 44.5, pos: 8 },
  ],
  Marty: [
    { team: 'CHI', ou: 'under', line: 37.5, pos: 1 },
    { team: 'SAS', ou: 'over', line: 28.5, pos: 2 },
    { team: 'UTA', ou: 'over', line: 35.5, pos: 3 },
    { team: 'HOU', ou: 'over', line: 31.5, pos: 4 },
    { team: 'MIA', ou: 'under', line: 44.5, pos: 5 },
    { team: 'SAC', ou: 'over', line: 44.5, pos: 6 },
    { team: 'MIL', ou: 'over', line: 53.5, pos: 7 },
    { team: 'POR', ou: 'over', line: 27.5, pos: 8 },
  ],
  'Ztanz Nation': [
    { team: 'CHA', ou: 'over', line: 31.5, pos: 1 },
    { team: 'ATL', ou: 'over', line: 42.5, pos: 2 },
    { team: 'BOS', ou: 'over', line: 54.5, pos: 3 },
    { team: 'MEM', ou: 'over', line: 44.5, pos: 4 },
    { team: 'PHI', ou: 'under', line: 47.5, pos: 5 },
    { team: 'DEN', ou: 'under', line: 52.5, pos: 6 },
    { team: 'DET', ou: 'under', line: 27.5, pos: 7 },
    { team: 'LAL', ou: 'under', line: 46.5, pos: 8 },
  ],
  Billy: [
    { team: 'MIL', ou: 'under', line: 53.5, pos: 1 },
    { team: 'MIN', ou: 'over', line: 44.5, pos: 2 },
    { team: 'TOR', ou: 'under', line: 37.5, pos: 3 },
    { team: 'NOP', ou: 'under', line: 44.5, pos: 4 },
    { team: 'NYK', ou: 'under', line: 45.5, pos: 5 },
    { team: 'WAS', ou: 'over', line: 23.5, pos: 6 },
    { team: 'CHI', ou: 'over', line: 37.5, pos: 7 },
    { team: 'LAC', ou: 'over', line: 45.5, pos: 8 },
  ],
  Adam: [
    { team: 'ORL', ou: 'over', line: 37.5, pos: 1 },
    { team: 'GSW', ou: 'over', line: 47.5, pos: 2 },
    { team: 'LAC', ou: 'under', line: 45.5, pos: 3 },
    { team: 'OKC', ou: 'over', line: 44.5, pos: 4 },
    { team: 'TOR', ou: 'over', line: 37.5, pos: 5 },
    { team: 'SAS', ou: 'under', line: 28.5, pos: 6 },
    { team: 'PHX', ou: 'over', line: 52.5, pos: 7 },
    { team: 'CHA', ou: 'under', line: 31.5, pos: 8 },
  ],
  Leftovers: [
    { team: 'WAS', ou: 'under', line: 23.5 },
    { team: 'UTA', ou: 'under', line: 35.5 },
    { team: 'ORL', ou: 'under', line: 37.5 },
    { team: 'IND', ou: 'under', line: 38.5 },
  ],
};

picksConst2023 = {
  Adam: [
    { team: 'Orlando Magic', ou: 'over', line: 26.5, pos: 1 },
    { team: 'Detroit Pistons', ou: 'over', line: 29.5, pos: 2 },
    { team: 'New York Knicks', ou: 'over', line: 38.5, pos: 3 },
    { team: 'Minnesota Timberwolves', ou: 'under', line: 48.5, pos: 4 },
    { team: 'Brooklyn Nets', ou: 'over', line: 50.5, pos: 5 },
    { team: 'Cleveland Cavaliers', ou: 'over', line: 47.5, pos: 6 },
    { team: 'Memphis Grizzlies', ou: 'under', line: 48.5, pos: 7 },
    { team: 'Phoenix Suns', ou: 'over', line: 52.5, pos: 8 },
  ],
  Zeus: [
    { team: 'Sacramento Kings', ou: 'over', line: 33.5, pos: 1 },
    { team: 'Philadelphia 76ers', ou: 'over', line: 50.5, pos: 2 },
    { team: 'Portland Trail Blazers', ou: 'under', line: 39.5, pos: 3 },
    { team: 'Atlanta Hawks', ou: 'over', line: 45.5, pos: 4 },
    { team: 'New York Knicks', ou: 'under', line: 38.5, pos: 5 },
    { team: 'Indiana Pacers', ou: 'over', line: 23.5, pos: 6 },
    { team: 'Washington Wizards', ou: 'over', line: 35.5, pos: 7 },
    { team: 'Milwaukee Bucks', ou: 'under', line: 52.5, pos: 8 },
  ],
  Billy: [
    { team: 'Denver Nuggets', ou: 'over', line: 49.5, pos: 1 },
    { team: 'Phoenix Suns', ou: 'under', line: 52.5, pos: 2 },
    { team: 'Dallas Mavericks', ou: 'under', line: 48.5, pos: 3 },
    { team: 'Houston Rockets', ou: 'over', line: 23.5, pos: 4 },
    { team: 'Memphis Grizzlies', ou: 'over', line: 48.5, pos: 5 },
    { team: 'Atlanta Hawks', ou: 'under', line: 45.5, pos: 6 },
    { team: 'Chicago Bulls', ou: 'over', line: 41.5, pos: 7 },
    { team: 'Cleveland Cavaliers', ou: 'under', line: 47.5, pos: 8 },
  ],
  Marty: [
    { team: 'Oklahoma City Thunder', ou: 'under', line: 23.5, pos: 1 },
    { team: 'Washington Wizards', ou: 'under', line: 35.5, pos: 2 },
    { team: 'Portland Trail Blazers', ou: 'over', line: 39.5, pos: 3 },
    { team: 'Houston Rockets', ou: 'under', line: 23.5, pos: 4 },
    { team: 'Brooklyn Nets', ou: 'under', line: 50.5, pos: 5 },
    { team: 'Sacramento Kings', ou: 'under', line: 33.5, pos: 6 },
    { team: 'Toronto Raptors', ou: 'under', line: 45.5, pos: 7 },
    { team: 'Charlotte Hornets', ou: 'over', line: 35.5, pos: 8 },
  ],
  Jesse: [
    { team: 'Boston Celtics', ou: 'under', line: 53.5, pos: 1 },
    { team: 'Charlotte Hornets', ou: 'under', line: 35.5, pos: 2 },
    { team: 'Milwaukee Bucks', ou: 'over', line: 52.5, pos: 3 },
    { team: 'Utah Jazz', ou: 'under', line: 24.5, pos: 4 },
    { team: 'Los Angeles Clippers', ou: 'under', line: 52.5, pos: 5 },
    { team: 'Miami Heat', ou: 'under', line: 48.5, pos: 6 },
    { team: 'Dallas Mavericks', ou: 'over', line: 48.5, pos: 7 },
    { team: 'Los Angeles Lakers', ou: 'over', line: 45.5, pos: 8 },
  ],
  Chris: [
    { team: 'San Antonio Spurs', ou: 'under', line: 22.5, pos: 1 },
    { team: 'Golden State Warriors', ou: 'over', line: 51.5, pos: 2 },
    { team: 'Indiana Pacers', ou: 'under', line: 23.5, pos: 3 },
    { team: 'Los Angeles Lakers', ou: 'under', line: 45.5, pos: 4 },
    { team: 'Los Angeles Clippers', ou: 'over', line: 52.5, pos: 5 },
    { team: 'Miami Heat', ou: 'over', line: 48.5, pos: 6 },
    { team: 'Minnesota Timberwolves', ou: 'over', line: 48.5, pos: 7 },
    { team: 'Oklahoma City Thunder', ou: 'over', line: 23.5, pos: 8 },
  ],
  Amir: [
    { team: 'New Orleans Pelicans', ou: 'over', line: 44.5, pos: 1 },
    { team: 'Toronto Raptors', ou: 'over', line: 45.5, pos: 2 },
    { team: 'San Antonio Spurs', ou: 'over', line: 22.5, pos: 3 },
    { team: 'Chicago Bulls', ou: 'under', line: 41.5, pos: 4 },
    { team: 'Golden State Warriors', ou: 'under', line: 51.5, pos: 5 },
    { team: 'Detroit Pistons', ou: 'under', line: 29.5, pos: 6 },
    { team: 'Philadelphia 76ers', ou: 'under', line: 50.5, pos: 7 },
    { team: 'Boston Celtics', ou: 'over', line: 53.5, pos: 8 },
  ],
  Leftovers: [
    { team: 'Denver Nuggets', ou: 'under', line: 49.5 },
    { team: 'New Orleans Pelicans', ou: 'under', line: 44.5 },
    { team: 'Orlando Magic', ou: 'under', line: 26.5 },
    { team: 'Utah Jazz', ou: 'over', line: 24.5 },
  ],
};

pickConst2022 = {
  Zeus: [
    { team: 'Washington Wizards', ou: 'over', line: 33.5, pos: 1 },
    { team: 'San Antonio Spurs', ou: 'over', line: 28.5, pos: 2 },
    { team: 'Houston Rockets', ou: 'under', line: 27.5, pos: 3 },
    { team: 'Phoenix Suns', ou: 'over', line: 51.5, pos: 4 },
    { team: 'Memphis Grizzlies', ou: 'over', line: 41.5, pos: 5 },
    { team: 'Miami Heat', ou: 'under', line: 48.5, pos: 6 },
    { team: 'Oklahoma City Thunder', ou: 'under', line: 23.5, pos: 7 },
    { team: 'Utah Jazz', ou: 'under', line: 51.5, pos: 8 },
  ],
  Chris: [
    { team: 'Utah Jazz', ou: 'over', line: 51.5, pos: 1 },
    { team: 'Brooklyn Nets', ou: 'over', line: 56.5, pos: 2 },
    { team: 'Minnesota Timberwolves', ou: 'under', line: 34.5, pos: 3 },
    { team: 'Orlando Magic', ou: 'under', line: 22.5, pos: 4 },
    { team: 'Chicago Bulls', ou: 'under', line: 42.5, pos: 5 },
    { team: 'Los Angeles Clippers', ou: 'over', line: 42.5, pos: 6 },
    { team: 'Detroit Pistons', ou: 'under', line: 24.5, pos: 7 },
    { team: 'Toronto Raptors', ou: 'under', line: 35.5, pos: 8 },
  ],
  Adam: [
    { team: 'Milwaukee Bucks', ou: 'over', line: 54.5, pos: 1 },
    { team: 'Houston Rockets', ou: 'over', line: 27.5, pos: 2 },
    { team: 'Philadelphia 76ers', ou: 'over', line: 50.5, pos: 3 },
    { team: 'Los Angeles Lakers', ou: 'over', line: 51.5, pos: 4 },
    { team: 'Golden State Warriors', ou: 'over', line: 48.5, pos: 5 },
    { team: 'Portland Trail Blazers', ou: 'under', line: 44.5, pos: 6 },
    { team: 'Sacramento Kings', ou: 'over', line: 36.5, pos: 7 },
    { team: 'Washington Wizards', ou: 'under', line: 33.5, pos: 8 },
  ],
  Billy: [
    { team: 'Cleveland Cavaliers', ou: 'over', line: 26.5, pos: 1 },
    { team: 'Brooklyn Nets', ou: 'under', line: 56.5, pos: 2 },
    { team: 'Memphis Grizzlies', ou: 'under', line: 41.5, pos: 3 },
    { team: 'New Orleans Pelicans', ou: 'under', line: 39.5, pos: 4 },
    { team: 'Toronto Raptors', ou: 'over', line: 35.5, pos: 5 },
    { team: 'New York Knicks', ou: 'under', line: 41.5, pos: 6 },
    { team: 'Boston Celtics', ou: 'over', line: 45.5, pos: 7 },
    { team: 'Phoenix Suns', ou: 'under', line: 51.5, pos: 8 },
  ],
  Amir: [
    { team: 'New York Knicks', ou: 'over', line: 41.5, pos: 1 },
    { team: 'Charlotte Hornets', ou: 'over', line: 38.5, pos: 2 },
    { team: 'Orlando Magic', ou: 'over', line: 22.5, pos: 3 },
    { team: 'Sacramento Kings', ou: 'under', line: 36.5, pos: 4 },
    { team: 'Boston Celtics', ou: 'under', line: 45.5, pos: 5 },
    { team: 'Dallas Mavericks', ou: 'over', line: 48.5, pos: 6 },
    { team: 'Indiana Pacers', ou: 'under', line: 42.5, pos: 7 },
    { team: 'Miami Heat', ou: 'over', line: 48.5, pos: 8 },
  ],
  Jesse: [
    { team: 'Atlanta Hawks', ou: 'over', line: 46.5, pos: 1 },
    { team: 'Denver Nuggets', ou: 'over', line: 47.5, pos: 2 },
    { team: 'Chicago Bulls', ou: 'over', line: 42.5, pos: 3 },
    { team: 'Philadelphia 76ers', ou: 'under', line: 50.5, pos: 4 },
    { team: 'Detroit Pistons', ou: 'over', line: 24.5, pos: 5 },
    { team: 'Cleveland Cavaliers', ou: 'under', line: 26.5, pos: 6 },
    { team: 'Charlotte Hornets', ou: 'under', line: 38.5, pos: 7 },
    { team: 'Minnesota Timberwolves', ou: 'over', line: 34.5, pos: 8 },
  ],
  Martin: [
    { team: 'Portland Trail Blazers', ou: 'over', line: 44.5, pos: 1 },
    { team: 'Los Angeles Clippers', ou: 'under', line: 42.5, pos: 2 },
    { team: 'Los Angeles Lakers', ou: 'under', line: 51.5, pos: 3 },
    { team: 'Golden State Warriors', ou: 'under', line: 48.5, pos: 4 },
    { team: 'Indiana Pacers', ou: 'over', line: 42.5, pos: 5 },
    { team: 'Oklahoma City Thunder', ou: 'over', line: 23.5, pos: 6 },
    { team: 'Milwaukee Bucks', ou: 'under', line: 54.5, pos: 7 },
    { team: 'Dallas Mavericks', ou: 'under', line: 48.5, pos: 8 },
  ],
  Leftovers: [
    { team: 'Atlanta Hawks', ou: 'under', line: 46.5 },
    { team: 'Denver Nuggets', ou: 'under', line: 47.5 },
    { team: 'New Orleans Pelicans', ou: 'over', line: 39.5 },
    { team: 'San Antonio Spurs', ou: 'under', line: 28.5 },
  ],
};
